### ISSUE TITLE
[Desktop][GUI][Aesthetics] Missing piece of image

### ISSUE THREAD

**Issue by qgithub11** [cyemekaray/WarbuildsPublic#11]
Class of defect: Aesthetics

Step reproduction:
 - Open Warbuilders
 - Resizing Window, on the horizontal axis

Result:
![Issue2](https://user-images.githubusercontent.com/63152068/78451133-e56ada80-7683-11ea-905c-89fd272bcaa0.png)

**Comment by cyemekaray** [comment]
fixed! made the window not resizable, so the dimensions are locked
